packaging_format = 2

id = "transfersh"
name = "Transfer.sh"
description.en = "Easy and fast file sharing from the command-line"
description.fr = "Partage de fichiers simple et rapide depuis la ligne de commande"

version = "1.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://transfer.sh/"
admindoc = "https://github.com/dutchcoders/transfer.sh/"
code = "https://github.com/dutchcoders/transfer.sh"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.4.0/transfersh-v1.4.0-linux-arm64-v8a"
        arm64.sha256 = "cc7c8e6d1b50dc18ee901a25222d2718cc752574e4b208876cd974a1e2870f12"
        amd64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.4.0/transfersh-v1.4.0-linux-amd64"
        amd64.sha256 = "c43eca70ce4106a4563858c74a6110ca800fab7c43ac359afd34c5131992c52b"
        armhf.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.4.0/transfersh-v1.4.0-linux-amd64"
        armhf.sha256 = "c43eca70ce4106a4563858c74a6110ca800fab7c43ac359afd34c5131992c52b"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
