packaging_format = 2

id = "transfersh"
name = "Transfer.sh"
description.en = "Easy and fast file sharing from the command-line"
description.fr = "Partage de fichiers simple et rapide depuis la ligne de commande"

version = "1.6.1~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://transfer.sh/"
admindoc = "https://github.com/dutchcoders/transfer.sh/"
code = "https://github.com/dutchcoders/transfer.sh"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.1/transfersh-v1.6.1-linux-arm64-v8a"
        arm64.sha256 = "4c2eb4bf63130d01f657a495a440919e0360f2eab5c7ab50d68ab07ca415d334"
        amd64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.1/transfersh-v1.6.1-linux-amd64"
        amd64.sha256 = "46fb5ac519769bae8a626cc3f79e2101013ff13beb75d5a613b8df6970d9e27c"
        armhf.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.1/transfersh-v1.6.1-linux-armv7"
        armhf.sha256 = "6caa016b908c5cd52224e871cfab58474e36a72c11932281f7a512650433ad3b"
        in_subdir = false
        extract = false
        rename = "transfersh"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^transfersh-.*-linux-amd64$"
        autoupdate.asset.arm64 = "^transfersh-.*-linux-arm64-v8a$"
        autoupdate.asset.armhf = "^transfersh-.*-linux-armv7$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "curl"
