packaging_format = 2

id = "transfersh"
name = "Transfer.sh"
description.en = "Easy and fast file sharing from the command-line"
description.fr = "Partage de fichiers simple et rapide depuis la ligne de commande"

version = "1.5.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://transfer.sh/"
admindoc = "https://github.com/dutchcoders/transfer.sh/"
code = "https://github.com/dutchcoders/transfer.sh"

[integration]
yunohost = ">= 11.1.17"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.5.0/transfersh-v1.5.0-linux-arm64-v8a"
        arm64.sha256 = "03ec909032fb07a43c30705aeba05b602ed90f5e632b6d9aabefd6f15d948816"
        amd64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.5.0/transfersh-v1.5.0-linux-amd64"
        amd64.sha256 = "b60d426444af83d889c66361e2f0ed2f3929fd07dc42f5ca61379fbff7c6fc99"
        armhf.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.5.0/transfersh-v1.5.0-linux-armv7"
        armhf.sha256 = "adc753ae69daa169103dd4de58070699a4ae96a468c064acd44263a7ce4c5fb4"
        in_subdir = false
        extract = false
        rename = "transfersh"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "transfersh-*-linux-amd64"
        autoupdate.asset.arm64 = "transfersh-*-linux-arm64-v8a"
        autoupdate.asset.armhf = "transfersh-*-linux-armv7"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "curl"
