packaging_format = 2

id = "transfersh"
name = "Transfer.sh"
description.en = "Easy and fast file sharing from the command-line"
description.fr = "Partage de fichiers simple et rapide depuis la ligne de commande"

version = "1.6.0~ynh4"

maintainers = []

[upstream]
license = "MIT"
website = "https://transfer.sh/"
admindoc = "https://github.com/dutchcoders/transfer.sh/"
code = "https://github.com/dutchcoders/transfer.sh"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.0/transfersh-v1.6.0-linux-arm64-v8a"
        arm64.sha256 = "6b1f09537aeaa6066c915e68afdabf7bfbd4237b6e9a9143b1d8a5d46fd9f502"
        amd64.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.0/transfersh-v1.6.0-linux-amd64"
        amd64.sha256 = "e3a582a38a4b6f581d1fa1c25c7176e2614a020fc635e2766bcf20a3e70974fe"
        armhf.url = "https://github.com/dutchcoders/transfer.sh/releases/download/v1.6.0/transfersh-v1.6.0-linux-armv7"
        armhf.sha256 = "64e19113d10cb4638b43dc95942b0c702e834ddf7011a96326fb1a0f4cca2f33"
        in_subdir = false
        extract = false
        rename = "transfersh"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^transfersh-.*-linux-amd64$"
        autoupdate.asset.arm64 = "^transfersh-.*-linux-arm64-v8a$"
        autoupdate.asset.armhf = "^transfersh-.*-linux-armv7$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "curl"
